spring:
    application:
        name: user-service
server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/user_db 
        username: user_admin # Placeholder
        password: password # Placeholder
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

COMPANY_SERVICE_URL: http://localhost:8080 

management:
    endpoints:
        web:
            exposure:
                include: "*" # Expose all actuator endpoints (adjust for production)
    endpoint:
        health:
            show-details: always
