spring:
    application:
        name: user-service
    datasource:
        url: jdbc:postgresql://localhost:5432/user_db 
        username: user_admin # Placeholder
        password: password # Placeholder
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8090
app:
    company-service-url: http://localhost:8091

management:
    endpoints:
        web:
            exposure:
                include: "*" # Expose all actuator endpoints (adjust for production)
    endpoint:
        health:
            show-details: always