server:
  port: 8090
spring:
  data:
    mongodb:
      username: bakhtiyor
      password: bakhtiyor
      host: mongodb
      port: 27017
      database: user_db
      authentication-database: admin

application:
  name: user-service
  config:
    company-url: http://localhost:8082/api/v1/companies
