server:
  port: 8080

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://postgres-user-db:5432/user_db
    username: user_admin
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect